---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: latest

resources:
  - name: hello_hapi
    type: git
    source: &repo-source
      uri: https://github.com/pedrofolim/hello_hapi
      branch: master
  - name: hello_hapi-docker-image
    type: docker-image
    source:
      email: nexus@sysmap.com.br
      username: admin
      password: admin123
      insecure_registries: nexus-registry-nexus.apps.quarks-dev.sysmap.io
      repository: nexus-registry-nexus.apps.quarks-dev.sysmap.io/poc/hello_hapi
      tag: 1.0.0
  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json

jobs:
  - name: Install dependencies
    plan:
      - get: hello_hapi
        trigger: true
      - get: dependency-cache
  - name: Build Feature
    plan:
      - get: hello_hapi
        trigger: true
        passed: [Install dependencies]
      - get: dependency-cache
        passed: [Install dependencies]
      - put: hello_hapi-docker-image
        params: {build: hello_hapi}
